config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  scope "(:locale)", :locale => /en|ru/ do
    devise_for :users
    root 'files#index'
    resources :files, only: [:index] do
      collection do
        post 'upload'
        get  'file_info'
        get  'check_state'
      end
    end
    resources :extensions, only: [:index]
    resources :users, only: [] do
      collection do
        get 'files_history'
      end
    end
  end
  get '/dropbox_auth', to: redirect('/dropbox_auth.html')
end

app/models/converted_file.rb
class ConvertedFile < ActiveRecord::Base
  mount_uploader :file, FileUploader

  belongs_to :user
  belongs_to :extension
end

app/models/extension.rb
class Extension < ActiveRecord::Base
  belongs_to :format

  has_many :extension_associations
  has_many :converted_extensions, through: :extension_associations
  has_many :inverse_extension_associations, class_name: "ExtensionAssociation", foreign_key: "converted_extension_id"
  has_many :inverse_extensions, through: :inverse_extension_associations, source: :extension
  has_many :converted_files
end

app/models/extension_association.rb
class ExtensionAssociation < ActiveRecord::Base
  belongs_to :extension
  belongs_to :converted_extension, class_name: "Extension"
end

app/models/format.rb
class Format < ActiveRecord::Base
  has_many :extensions, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :converted_files

  def serialize
    UserSerializer.new(self, root: false).to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def default_url_options(options={})
    { locale: I18n.locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        << [:name, :lastname]
    devise_parameter_sanitizer.for(:account_update) << [:name, :lastname]
  end

  def set_locale
    I18n.locale = params[:locale] || "en"
  end
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  def index
    extensions = ExtensionService.prepare_extensions(params[:format])
    if extensions && extensions.present?
      render json: extensions,  status: :ok
    else
      render json: { error: t('.error') }, status: :not_acceptable
    end
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def index
  end

  def upload
    file = UploadService.upload(params, current_user) if ExtensionService.check_extension(params[:file], params[:extension_to])
    if file
      render json: file, serializer: FileUploadSerializer, status: :ok
    else
      render json: { error: t('.error') }, status: :not_acceptable
    end
  end

  def file_info
    info = FileService.info_from_url(params[:url])
    if info
      render json: info, status: :ok
    else
      render json: { error: t('.error') }, status: :not_acceptable
    end
  end

  def check_state
    state = FileService.check_state(params[:id])
    if state
      render json: state, status: :ok
    else
      render json: { error: t('.error') }, status: :not_acceptable
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def files_history
    respond_to do |format|
      format.html { render 'users/files_history' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/files/index.html.haml
%div.select-file-page(ng-controller="FilesCtrl" uploader-callbacks bs-alert)
  %div.row
    %div(class="col-md-8 col-md-offset-2")
      %h3(style="text-align: center;") {{ 'header' | translate }}
    %div.buttons-row(class="col-md-8 col-md-offset-2")
      %input#file-uploader(type="file" nv-file-select uploader="uploader" multiple)
      %button.btn.btn-primary(ng-click="uploadFile()") {{ 'computer' | translate }}
      %button.btn.btn-primary(ng-click="openUploadFromUrl()") {{ 'url' | translate }}
      %dropbox-chooser
      %google-drive-chooser
  %div.row
    %div(class="col-md-8 col-md-offset-2" style="text-align: center;")
      %h5 {{ 'dropzone' | translate }}

  %div.row
    %div(class="col-md-8 col-md-offset-2 drag-drop" nv-file-drop uploader="uploader")
      %div.file-table(ng-repeat="item in uploader.queue")
        %div.file-table-cell.filename
          {{ item.file.name | cut:true:30 }}
        %div.file-table-cell.size
          {{ item.file.size | bytes }}
        %div.file-table-cell.select-format(ng-show="item.file.extensions")
          %select.form-control(ng-model="item.file.extension_to" ng-options="extension.extension group by extension.format for extension in item.file.extensions")
        %div.file-table-cell.status(ng-show="item.file.status")
          %span(ng-show="item.file.status == 'uploaded' || item.file.status == 'uploading'")
            %img(src="/assets/converter_load.gif")
          %span.text(ng-class="item.file.status") {{ item.file.status }}
        %div.file-table-cell.download-action(ng-show="item.file.download_url")
          %a.btn.btn-success(ng-href="{{item.file.download_url}}" target="_blank") {{ 'download' | translate }}
        %div.file-table-cell.remove-action
          %span(class="fa fa-times cursor-pointer" aria-hidden="true" ng-click="uploader.removeFromQueue(item)")
    %div(ng-hide="uploader.queue.length == 0" ng-disabled="uploader.queue.length == 0")
      %div(class="col-md-2 col-md-offset-5")
        %dropbox-saver
      %div(class="col-md-2 col-md-offset-5")
        %google-drive-saver
      %div(class="col-md-2 col-md-offset-5")
        %input(type="checkbox" ng-checked="sendEmail" ng-click="sendNotification()") {{ 'send_email' | translate }}
        %div(ng-show="sendEmail")
          %span {{ 'email' | translate }}
          %input(type="text" ng-model="email")
      %div(class="col-md-2 col-md-offset-5")
        %button.btn.btn-danger.convert-button(ng-click="uploader.uploadAll()") {{ 'convert' | translate }}

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    %nav
      %ul.nav.navbar-nav.navbar-left
        %li
          = link_to "File Converter", root_path, method: :get
        %li
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = t('locale_name')
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to 'English', url_for(locale: 'en'), method: :get
                = link_to 'Русский', url_for(locale: 'ru'), method: :get

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              = current_user.email
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to t('files_history'), files_history_users_path, method: :get
                = link_to t('edit_account'), edit_user_registration_path, method: :get
              %li
                = link_to t('log_out'), destroy_user_session_path, method: :delete
        - else
          %li= link_to t('sign_up'), new_user_registration_path, method: :get
          %li= link_to t('sign_in'), new_user_session_path, method: :get

app/views/layouts/application.html.haml
!!!
%html(ng-app="mainApp")
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FileConverter
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'http://apis.google.com/js/client.js'
    = javascript_include_tag 'http://apis.google.com/js/api.js'
    = javascript_include_tag 'https://www.dropbox.com/static/api/2/dropins.js', 'id': 'dropboxjs', 'data-app-key': 'yz2smng2q90mc3e'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/dropbox.js/0.10.3/dropbox.min.js'
    = csrf_meta_tags
  %body
    %language-select
    = render 'layouts/header'
    %div.container
      = yield

app/views/users/files_history.html.haml
%div(ng-controller="UsersCtrl" ng-init="init('#{current_user.serialize}')")
  %table.table.table-striped(st-table="files")
    %thead
      %tr
        %th(st-sort="filename") {{ 'filename' | translate }}
        %th(st-sort="format") {{ 'format' | translate }}
        %th(st-sort="extension") {{ 'extension' | translate }}
        %th(st-sort="created_at" st-sort-default="reverse") {{ 'created_at' | translate }}
        %th(st-sort="state") {{ 'state' | translate }}
        %th
      %tr
        %th
          %input.input-sm.form-control(st-search="filename" type="search")
        %th
          %input.input-sm.form-control(st-search="format" type="search")
        %th
          %input.input-sm.form-control(st-search="extension" type="search")
        %th
          %input.input-sm.form-control(st-search="created_at" type="search")
        %th
          %input.input-sm.form-control(st-search="state" type="search")
        %th
    %tbody
      %tr(ng-repeat="file in files")
        %td {{file.filename}}
        %td {{file.format}}
        %td {{file.extension}}
        %td {{file.created_at | date }}
        %td
          %span.text(ng-class="file.state") {{file.state}}
        %td
          %a.btn.btn-success(href="{{file.download_url}}" ng-if="file.download_url") {{ 'download' | translate }}